# Built with Jekyll 3.2.0

# Setup
title:               Insurgencia 2.0
tagline:             construcción de paz a través de Memes
description:         Insurgencia 2.0 es una herramienta para docentes y líderes sociales para pensar el Meme como herramienta de construcción de paz.
url:                 'http://elotroalex.github.io'
baseurl:             '/insurgencia2punto0'

# About/contact
author:
  name:              Joao Gabriel ALmeida
  url:
  email:             jgabrielrtalmeida@gmail.com

# Permalinks

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme:

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor

# Theme
theme: "ed."
